- name: install some tools
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: present
  vars:
    packages:
      - apt-transport-https
      - git
      - curl
      - fzf
      - wget
      - pw-gen
      - rsync
      - tcpdump